[package]
name = "example-ffi"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
serde = "1.0.9"
serde_json = "1.0.9"
libc = "0.2"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "example-ffi"
path = "src/main.rs"
