[package]
name = "core"
version = "0.1.0"
edition = "2021"

# TODO
# [[test]]
# name = "merge_prep_tests"
# path = "tests/prep/remove_comments.rs"

[dependencies]
bytestring = "1.3.0"
regex = "1.9.6"
thiserror = "1.0.49"
log = "0.4.20"
